using System.Text.Json.Serialization;

namespace BlueBubbles.Core.Models;

public record Message(
    [property: JsonPropertyName("originalROWID")] int? OriginalRowId,
    [property: JsonPropertyName("guid")] string Guid,
    [property: JsonPropertyName("handleId")] int? HandleId,
    [property: JsonPropertyName("otherHandle")] int? OtherHandle,
    [property: JsonPropertyName("text")] string? Text,
    [property: JsonPropertyName("subject")] string? Subject,
    [property: JsonPropertyName("country")] string? Country,
    [property: JsonPropertyName("error")] int Error,
    [property: JsonPropertyName("dateCreated")] long? DateCreated,
    [property: JsonPropertyName("dateRead")] long? DateRead,
    [property: JsonPropertyName("dateDelivered")] long? DateDelivered,
    [property: JsonPropertyName("isDelivered")] bool IsDelivered,
    [property: JsonPropertyName("isFromMe")] bool IsFromMe,
    [property: JsonPropertyName("hasDdResults")] bool HasDdResults,
    [property: JsonPropertyName("datePlayed")] long? DatePlayed,
    [property: JsonPropertyName("itemType")] int ItemType,
    [property: JsonPropertyName("groupTitle")] string? GroupTitle,
    [property: JsonPropertyName("groupActionType")] int GroupActionType,
    [property: JsonPropertyName("balloonBundleId")] string? BalloonBundleId,
    [property: JsonPropertyName("associatedMessageGuid")] string? AssociatedMessageGuid,
    [property: JsonPropertyName("associatedMessagePart")] int? AssociatedMessagePart,
    [property: JsonPropertyName("associatedMessageType")] string? AssociatedMessageType,
    [property: JsonPropertyName("expressiveSendStyleId")] string? ExpressiveSendStyleId,
    [property: JsonPropertyName("handle")] Handle? Handle,
    [property: JsonPropertyName("hasAttachments")] bool HasAttachments,
    [property: JsonPropertyName("hasReactions")] bool HasReactions,
    [property: JsonPropertyName("dateDeleted")] long? DateDeleted,
    [property: JsonPropertyName("metadata")] Dictionary<string, object?>? Metadata,
    [property: JsonPropertyName("threadOriginatorGuid")] string? ThreadOriginatorGuid,
    [property: JsonPropertyName("threadOriginatorPart")] string? ThreadOriginatorPart,
    [property: JsonPropertyName("attachments")] List<Attachment>? Attachments,
    [property: JsonPropertyName("chats")] List<Chat>? Chats,
    [property: JsonPropertyName("attributedBody")] List<AttributedBody>? AttributedBody,
    [property: JsonPropertyName("messageSummaryInfo")] List<MessageSummaryInfo>? MessageSummaryInfo,
    [property: JsonPropertyName("payloadData")] PayloadData? PayloadData,
    [property: JsonPropertyName("hasApplePayloadData")] bool HasApplePayloadData,
    [property: JsonPropertyName("dateEdited")] long? DateEdited,
    [property: JsonPropertyName("wasDeliveredQuietly")] bool WasDeliveredQuietly,
    [property: JsonPropertyName("didNotifyRecipient")] bool DidNotifyRecipient,
    [property: JsonPropertyName("isBookmarked")] bool IsBookmarked
);
